//! 跨端 DTO 类型生成检查。手写前端类型只保留本地 UI helper，后端契约从这里导出。

use std::path::PathBuf;
use ts_rs::TS;

fn generated_backend_types() -> String {
    let mut output = String::from(
        "/* eslint-disable */\n// This file is generated by ts-rs. Do not edit by hand.\n\n",
    );

    push::<crate::error::AppErrorKind>(&mut output);
    push::<crate::error::AppError>(&mut output);

    push::<crate::config::FireKeyMode>(&mut output);
    push::<crate::config::KeyBinding>(&mut output);
    push::<crate::config::EffectRule>(&mut output);
    push::<crate::config::ComboAction>(&mut output);
    push::<crate::config::ComboDefinition>(&mut output);
    push::<crate::config::ComboValidationField>(&mut output);
    push::<crate::config::ComboValidationIssue>(&mut output);
    push::<crate::config::ClassConfig>(&mut output);
    push::<crate::config::CustomConfig>(&mut output);
    push::<crate::config::DetectionNoMatchPolicy>(&mut output);
    push::<crate::config::DetectionSettings>(&mut output);
    push::<crate::config::LogLevelSetting>(&mut output);
    push::<crate::config::Hotkey>(&mut output);
    push::<crate::config::WindowPosition>(&mut output);
    push::<crate::config::FloatingControlSettings>(&mut output);
    push::<crate::config::AutoRunConfig>(&mut output);
    push::<crate::config::SettingsConfig>(&mut output);
    push::<crate::config::ProfilesConfig>(&mut output);

    push::<crate::domain::classes::ClassInfo>(&mut output);
    push::<crate::domain::classes::ClassCategory>(&mut output);
    push::<crate::domain::ConfigOption>(&mut output);
    push::<crate::domain::ClassInfoView>(&mut output);
    push::<crate::domain::ClassCategoryView>(&mut output);
    push::<crate::domain::ClassDisplayState>(&mut output);
    push::<crate::domain::CustomConfigDisplayState>(&mut output);
    push::<crate::domain::ProfileDisplaySnapshot>(&mut output);

    push::<crate::runtime::RuntimeEffectiveProfile>(&mut output);
    push::<crate::runtime::RuntimeStateSnapshot>(&mut output);
    push::<crate::runtime::RuntimeStatusSnapshot>(&mut output);
    push::<crate::runtime::AppStateSnapshot>(&mut output);
    push::<crate::runtime::AssistantRuntimeSnapshot>(&mut output);
    push::<crate::runtime::AssistantEngineSnapshots>(&mut output);

    push::<crate::engines::autofire::AutoFireKeySnapshot>(&mut output);
    push::<crate::engines::autofire::AutoFireSnapshot>(&mut output);
    push::<crate::engines::combo::ComboSnapshot>(&mut output);
    push::<crate::engines::autorun::AutoRunSnapshot>(&mut output);
    push::<crate::vision::detection::ClassDetectionResultEvent>(&mut output);
    push::<crate::vision::detection::DetectionSnapshot>(&mut output);

    push::<crate::ipc::bootstrap::BootstrapRuntimeState>(&mut output);
    push::<crate::ipc::bootstrap::BootstrapEffectiveProfile>(&mut output);
    push::<crate::ipc::bootstrap::BootstrapState>(&mut output);
    push::<crate::ipc::diagnostics::ForegroundDiagnostics>(&mut output);
    push::<crate::ipc::diagnostics::ActiveConfigDiagnostics>(&mut output);
    push::<crate::ipc::diagnostics::AutoRunDiagnostics>(&mut output);
    push::<crate::ipc::diagnostics::DetectionResultDiagnostics>(&mut output);
    push::<crate::ipc::diagnostics::DetectionDiagnostics>(&mut output);
    push::<crate::ipc::diagnostics::RuntimeDiagnostics>(&mut output);

    output
}

fn push<T: TS>(output: &mut String) {
    output.push_str("export ");
    output.push_str(&T::decl());
    output.push_str("\n\n");
}

fn generated_file_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("src")
        .join("generated")
        .join("backend-types.ts")
}

#[test]
fn generated_backend_types_are_current() {
    let expected = generated_backend_types();
    let path = generated_file_path();
    let actual = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        actual, expected,
        "generated backend types are stale; run `pnpm generate:types`"
    );
}

#[test]
#[ignore]
fn write_generated_backend_types() {
    let path = generated_file_path();
    std::fs::create_dir_all(path.parent().expect("generated file should have parent")).unwrap();
    std::fs::write(path, generated_backend_types()).unwrap();
}
